### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by s-kostyaev**
Add github actions CI

### CODE REVIEW

**Comment by s-kostyaev** [comment]
It kinda works https://github.com/s-kostyaev/llm/actions/runs/8024702759?pr=1 @ahyatt

**Comment by ahyatt** [comment]
Thank you, I really appreciate this, and it looks very useful.

A concern I have from looking at the code, is that I don't think it is correct or desirable to have package statements on files that are not the main package file.  Perhaps when I try this out myself I can see some way to disable some specific check.  WDYT?

**Comment by s-kostyaev** [comment]
I think the same. See https://github.com/s-kostyaev/llm/pull/2

**Comment by s-kostyaev** [comment]
It should work - https://github.com/leotaku/elisp-check/issues/19
But it didn't. Maybe I will try to continue tomorrow

**Comment by s-kostyaev** [comment]
Maybe related - https://github.com/leotaku/elisp-check/issues/22

**Comment by s-kostyaev** [comment]
Done. @ahyatt feel free to fix warnings from CI yourself 😄

**Comment by ahyatt** [comment]
Thank you for the contribution!  I'll go through how it is working and fix any issues I see.

**Pull request merged**
