### PR TITLE
Add support for auth-source secret functions to :key argument

### PR DESCRIPTION
**Pull request by minad**
Implements #110

### CODE REVIEW

**Comment by ahyatt** [comment]
This seems reasonable, thanks for adding it - can you also add it to Claude and Gemini, both of which use keys, plus note it in the README (perhaps with an usage example)?

**Comment by gs-101** [comment]
Also "Implements" is not a [PR keyword](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests). Use "close"/"closes" if you want to close #110 automatically :)

**Comment by ahyatt** [comment]
@gs-101 if you'd like to send a PR about that, that's be welcome, thank you!   Is there a relation to this PR, though?  Like, is it only possible after we can use auth sources for keys?

**Comment by gs-101** [comment]
> @gs-101 if you'd like to send a PR about that, that's be welcome, thank you! Is there a relation to this PR, though? Like, is it only possible after we can use auth sources for keys?

It would certainly help (since it would be easier to keep the key private), but it is not that related. Sorry for adding off-topic messages to the discussion, I just commented on it since I saw an opportunity after I joined the discussion with my previous comment. But I'll open up a PR to keep this unrelated topic from being discussed here.

**Comment by ahyatt** [comment]
@minad, if you can't make the changes, I'll merge this in a few days and finish the changes I suggested, which is fine.  This would be good to get into the next release.

**Comment by minad** [comment]
Thanks. I don't have much time right now.

**Pull request merged**
