### PR TITLE
Plz

### PR DESCRIPTION
**Pull request by r0man**
Hi @ahyatt,

we now have a release of plz: https://github.com/alphapapa/plz.el/pull/50

It's not on ELPA yet, but I hope this is done by some cron job that runs eventually.

This PR removes the vendored plz.el and adds it to the package requires.

### CODE REVIEW

**Comment by ahyatt** [comment]
I'm happy to see this go in, thank you!  Next step, I think, is to make sure the emacs-devel list is fine with your plan to eventually release the various handles you have as a separate GNU ELPA package, specifically for `plz`.  Once we're sure that they think it is reasonable, then we're good to go on my side.

**Comment by r0man** [comment]
Hi @ahyatt,

the ELPA maintainers are fine with adding plz-media-type and plz-event-source to ELPA. We actually have it already: 
https://git.savannah.gnu.org/cgit/emacs/elpa.git/log/

Once we are fine everything works as expected with the vendored libraries we can remove the `-pre` from the libraries and they will be released as official packages.

Roman

**Comment by ahyatt** [comment]
Excellent, thank you!  Can these be required via `package-requires` now, in their `-pre` state?

**Comment by r0man** [comment]
No, until they are released they should not  be added to the package-requires section, otherwise tools might try to install the libraries from some package archive and fail.

**Comment by ahyatt** [comment]
I am still not seeing your packages in GNU ELPA.  Do you know what is going on with that?

**Comment by r0man** [comment]
Hi @ahyatt,

Philip added both libraries into the ELPA Git repository 2 weeks ago. I put you on CC in this conversation.

https://lists.gnu.org/archive/html/emacs-devel/2024-05/msg00015.html
https://git.savannah.gnu.org/cgit/emacs/elpa.git/log/

They won't appear on the ELPA website until I remove the `-pre` suffix from the version. 

I'm still under the assumption that we ship plz-media-type and plz-event-source with the llm library initially and release them to ELPA once we are sure there aren't any serious flaws. The timeline being half a year, as we discussed. 

I'm using the plz branch of the llm library since 2 weeks now with the OpenAI and my custom OpenAI provider. I haven't noticed anything wrong. So those are good to go.

Did you had the chance to test the other providers using the plz branch?

What's the plan?

**Comment by ahyatt** [comment]
Thanks, I did see that conversation, but forgot about the resolution.  I need to resolve an issue with the llm version, and then I'll merge the `plz` branch to main and push it out.  I'm fairly busy this week, so hopefully that can happen near the end of the week or the weekend.

**Comment by r0man** [comment]
Ok, cool. I'm looking forward to it!

**Comment by leotaku** [comment]
As far as I can see, both plz-media-type and plz-event-source are now available on GNU ELPA. Would you welcome a PR that un-vendors these packages?

**Comment by ahyatt** [comment]
I believe @r0man wanted some time to be sure there aren't any flaws.  It's been a few months since we heard of any issue, so I think it probably does make sense to un-vendor them.  @r0man, what do you think?

**Comment by r0man** [comment]
Hi @ahyatt and @leotaku , 

yes, I think we could unbundle them. I tagged the plz-media-type and plz-event-source libraries a while ago with a version and published them to ELPA, because I was using them also in another project.

Nothing should have changed functionality wise from the bundled version we have in the llm library.
I'm a bit busy at the moment, and just haven't got around un-bundling this myself.

So if you would like to do it @leotaku , please go ahead!

Thanks, Roman.

**Pull request merged**
