### PR TITLE
fixing some typos in readme

### PR DESCRIPTION
**Pull request by tvraman**
readme

### CODE REVIEW

**Comment by ahyatt** [comment]
Would it be possible to separate out the whitespace changes?  This leaves the file in a state where part of the file has long lines, the other part has short lines.  And it makes it difficult to understand the fixes you are making.

**Comment by tvraman** [comment]
Fixed one typo and repushed without WS changes.

The other piece I  originally fixed -- is in the middle of one of those
long lines -- search for "examples of this example" ...
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by ahyatt** [comment]
Thanks! I think your latest change reverted the edits as well.  I now see the issues you point out, but if I look at the total diff of the merge request, there is no diff, and the issues are still there, or at least the one you pointed out was still there.  Can you please re-fix the issues you initially fixed (while keeping whitespace the same)?

**Comment by tvraman** [comment]
I likely got distracted and confused myself. At this point I'll just
delete the PRAISEWORTHINESS, it is likely too heavy-weight a hammer at
this point since you know the issues:-)

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by ahyatt** [comment]
Yep, thank you for pointing them out!  I'll fix them shortly.

**Pull request closed without merging**
