### PR TITLE
Added ollama api key option

### PR DESCRIPTION
**Pull request by shaohme**
I just needed Bearer token authentication for my Ollama instance, so I added it. 
Hope it will be included, or something better proposed.

### CODE REVIEW

**Comment by ahyatt** [comment]
Thank you for contributing!  I think at the least, we shouldn't be providing a header if there is no key.  And can you tell me the background why you need a key to access Ollama?  I'm just trying to figure out how much of an edge case this is, because perhaps it might turn out that there's a variety of potential ways to authenticate with Ollama, and we need to accommodate all of them potentially..

**Comment by shaohme** [comment]
It is probably an edge case as many users probably hosts their Ollama instance locally on their workstation. I happen to host my Ollama instance remotely on a server and share it with my smartphone. The smartphone app supports adding a Bearer token as authentication so I configured that on the server which is why I need it configured on my Emacs too.

**Comment by ahyatt** [comment]
I wonder if we could just have documentation on how to customize things for these more unusual situations.  For example, I think you should be able to do this in your config:

```emacs-lisp
(cl-defstruct (llm-authed-ollama (:include llm-ollama)) key)
(cl-defmethod llm-provider-headers ((provider llm-authed-ollama))
  `(("Authorization" . ,(format "Bearer %s" (llm-authed-ollama-key provider)))))
```

And then use `(make-llm-authed-ollama :chat-model "llama3.1:latest" :key <your-key>)`.  Can you see if this would work for you?

**Comment by shaohme** [comment]
That results in:
``` elisp
error("Keyword argument %s not one of (:default-chat-temp..." :key)
```
when starting Emacs and using packages from melpa-stable.

Furthermore, shouldn't this be consistent with other providers? ```(llm-vertex)``` already got a ```:key``` argument.

**Comment by ahyatt** [comment]
It would be odd to have a `:key` argument in ollama, which normally doesn't need any authentication.  Authentication can be done a few different ways, so I think the less assumptions we make the better.  For example, for Vertex, there is no key, but there is a project id that you can get a key with via a command-line utility.  For Azure, there is a key, but it's passed as an `api-key` header.  For Gemini, the key is passed on the URL.  

I'm not sure what might be causing the issue you mentioned above, I did verify that it works, though, by looking at the request when running the following:

```emacs-lisp
(require 'llm-ollama)
(cl-defstruct (llm-authed-ollama (:include llm-ollama)) key)
(cl-defmethod llm-provider-headers ((provider llm-authed-ollama))
  `(("Authorization" . ,(format "Bearer %s" (llm-authed-ollama-key provider)))))

(llm-chat (make-llm-authed-ollama :chat-model "llama3.1:8b-instruct-q8_0" :key "key")
          (llm-make-chat-prompt "Give me the names of 5 D&D orcs"))
```

You should change the model, but otherwise can you run this and see if it works for you?  I suspect there might be some error on how you've integrated this into your `.emacs`.

**Comment by shaohme** [comment]
It works now. My mistake. Had some naming issues.

I'm fine with this approach 🙂 It serves the purpose and scratches my little itch.

I will close PR for now.

**Comment by ahyatt** [comment]
I'll add this the wiki here as an example of solving this problem.  Thank you for bringing this issue to my attention!

**Pull request closed without merging**
